version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db

  # MongoDB Express (Interface web)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

  # AdminMongo (Interface web alternative)
  adminmongo:
    image: mrvautin/adminmongo:latest
    ports:
      - "1234:1234"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - DB_HOST=mongo
      - DB_PORT=27017
    depends_on:
      - mongo

volumes:
  mongo_data:

